openapi: 3.0.3
info:
  title: Store API v1
  description: A RESTful database API for namespace, table, and data management. Includes a default 'takoc' namespace for system metadata.
  version: 1.0.0
servers:
  - url: /api/v1
    description: Default API server

tags:
  - name: Namespace
    description: Operations related to namespace management
  - name: Table
    description: Operations related to table management within namespaces
  - name: Record
    description: Operations related to record management within tables

components:
  schemas:
    NamespaceData:
      type: object
      properties:
        name:
          type: string
          description: Name of the namespace
        description:
          type: string
          description: Description of the namespace
      required:
        - name
    NamespaceCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the namespace
          minLength: 1
          maxLength: 50
        description:
          type: string
          description: Description of the namespace
      required:
        - name
    NamespaceUpdateRequest:
      type: object
      properties:
        description:
          type: string
          description: Description of the namespace
    TableData:
      type: object
      properties:
        name:
          type: string
          description: Name of the table
        namespace:
          type: string
          description: Name of the parent namespace
        description:
          type: string
          description: Description of the table
      required:
        - name
        - namespace
    TableCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the table
          minLength: 1
          maxLength: 50
        description:
          type: string
          description: Description of the table
      required:
        - name
    TableUpdateRequest:
      type: object
      properties:
        description:
          type: string
          description: Description of the table
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message for human consumption
        type:
          type: string
          description: Error type for programmatic handling
        data:
          type: object
          description: Additional error data
          nullable: true
      required:
        - message
        - type

paths:
  /namespace:
    post:
      tags: [ "Namespace" ]
      summary: Create a new namespace
      description: "Create a new namespace for organizing tables. Note: The system already provides a default 'takoc' namespace for system metadata management."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NamespaceCreateRequest"
      responses:
        "201":
          description: Namespace created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NamespaceData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags: [ "Namespace" ]
      summary: List all namespaces
      description: Get a list of all namespaces
      responses:
        "200":
          description: List of namespaces
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NamespaceData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /namespace/{namespace}:
    get:
      tags: [ "Namespace" ]
      summary: Get a namespace by name
      description: Retrieve a specific namespace by its name
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
      responses:
        "200":
          description: Namespace details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NamespaceData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [ "Namespace" ]
      summary: Update a namespace
      description: Update an existing namespace
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NamespaceUpdateRequest"
      responses:
        "200":
          description: Namespace updated successfully
          content:
            application/json:
              schema: { }
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [ "Namespace" ]
      summary: Delete a namespace
      description: Delete an existing namespace
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
      responses:
        "204":
          description: Namespace deleted successfully
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /table/{namespace}:
    post:
      tags: [ "Table" ]
      summary: Create a new table
      description: Create a new table within a namespace
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TableCreateRequest"
      responses:
        "201":
          description: Table created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableData"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Namespace not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags: [ "Table" ]
      summary: List tables in a namespace
      description: Get a list of all tables within a namespace
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
      responses:
        "200":
          description: List of tables
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TableData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Namespace not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /table/{namespace}/{table}:
    get:
      tags: [ "Table" ]
      summary: Get a table by name
      description: Retrieve a specific table by its name
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
      responses:
        "200":
          description: Table details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [ "Table" ]
      summary: Update a table
      description: Update an existing table
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TableUpdateRequest"
      responses:
        "200":
          description: Table updated successfully
          content:
            application/json:
              schema: { }
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [ "Table" ]
      summary: Delete a table
      description: Delete an existing table
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
      responses:
        "204":
          description: Table deleted successfully
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /data/{namespace}/{table}:
    get:
      tags: [ "Record" ]
      summary: List records in a table
      description: Get a list of all records within a table
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
      responses:
        "200":
          description: List of record IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /data/{namespace}/{table}/{record_id}:
    post:
      tags: [ "Record" ]
      summary: Create a record
      description: Create a new record in a table
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
        - in: path
          name: record_id
          required: true
          schema:
            type: string
          description: ID of the record
      requestBody:
        required: true
        content:
          application/json:
            schema: { }
      responses:
        "201":
          description: Record created successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags: [ "Record" ]
      summary: Get a record by ID
      description: Retrieve a specific record by its ID
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
        - in: path
          name: record_id
          required: true
          schema:
            type: string
          description: ID of the record
      responses:
        "200":
          description: Record data
          content:
            application/json:
              schema: { }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags: [ "Record" ]
      summary: Update a record
      description: Update an existing record
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
        - in: path
          name: record_id
          required: true
          schema:
            type: string
          description: ID of the record
      requestBody:
        required: true
        content:
          application/json:
            schema: { }
      responses:
        "200":
          description: Record updated successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [ "Record" ]
      summary: Delete a record
      description: Delete an existing record
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
          description: Name of the namespace
        - in: path
          name: table
          required: true
          schema:
            type: string
          description: Name of the table
        - in: path
          name: record_id
          required: true
          schema:
            type: string
          description: ID of the record
      responses:
        "204":
          description: Record deleted successfully
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
